yiisoft/app-api

- .github/workflows/build.yml
- .github/workflows/static.yml
> Fix pipeline

- composer.json
- src/Service/UserService.php
| Fixed issues  | https://github.com/yiisoft/yii-web/pull/334
> Switch to user package

- .github/workflows/build.yml
- tests/acceptance.suite.yml
> Add tests to pipeline

- .github/workflows/build.yml
- .github/workflows/static.yml
- .scrutinizer.yml
> Add test composer create project

- public/index-test.php
- public/index.php
| Fixed issues  | https://github.com/yiisoft/yii-console/pull/89
> Serve existing files directly by PHP built-in server

- config/params.php
- config/routes.php
- config/web/auth.php
- public/index-test.php
- src/Auth/AuthController.php
- src/Auth/AuthRequest.php
- src/Blog/BlogController.php
- src/Blog/BlogService.php
- src/Blog/EditPostRequest.php
- src/Blog/Post.php
- src/Blog/PostBuilder.php
- src/Blog/PostFormatter.php
- src/Blog/PostRepository.php
- src/Blog/PostStatus.php
- src/Blog/ViewPostRequest.php
- src/InfoController.php
- src/Provider/RepositoryProvider.php
- src/User/User.php
- src/User/UserController.php
- src/User/UserFormatter.php
- src/User/UserRepository.php
- src/User/UserService.php
> Group classes by use-case

- data/nginx/default.conf
> Fix docker nginx config for swagger

- src/Auth/AuthController.php
- src/Auth/AuthRequest.php
- src/Dto/ApiResponseData.php
- src/Factory/ApiResponseDataFactory.php
> Add open api docs for auth controller

- .gitignore
- codeception.yml
- composer.json
- public/index-test.php
> Add code coverage.

- config/routes.php
- src/Auth/AuthController.php
- src/Blog/BlogController.php
- src/Blog/BlogService.php
- src/Blog/EditPostRequest.php
- src/Blog/PageRequest.php
- src/User/UserRequest.php
- src/User/UserService.php
- tests/acceptance/AuthCest.php
> Fix logout user

- src/Blog/BlogController.php
- src/Blog/PageRequest.php
- src/Blog/PostFormatter.php
- src/Formatter/PaginatorFormatter.php
> Add open api docs for blog controller

- src/User/UserRepository.php
| Fixed issues  | https://github.com/yiisoft/data/pull/66
> Specify Sort fields

- README.md
- src/Auth/AuthController.php
- src/Blog/BlogController.php
- src/Blog/EditPostRequest.php
- src/InfoController.php
- src/User/UserController.php
- src/User/UserFormatter.php
> Add open api docs

- composer.json
- public/index.php
> Conditional rebuilding

- .gitattributes
> Modify list of ignored file when creating an archive

- config/routes.php
- src/Exception/BadRequestException.php
- src/Exception/MethodNotAllowedException.php
- src/Factory/RestGroupFactory.php
- src/RestControllerTrait.php
- src/User/UserController.php
- tests/acceptance/UserCest.php
| Fixed issues  | https://github.com/yiisoft/yii-api/issues/77
> Add rest group

- src/Blog/PostRepository.php
- src/User/UserRepository.php
> Update cycle-related code

- .github/workflows/build.yml
> Use composer update for build

- config/web/application.php
- config/web/error-handler.php
Waiting: https://github.com/yiisoft/error-handler/pull/25
> Fix config due to yiisoft/error-handler changes

- src/User/UserService.php
See https://github.com/yiisoft/user/pull/24
> Adopt to yiisoft/user PR #24

- .scrutinizer.yml
- composer.json
- public/index-test.php
- public/index.php
- src/ApplicationRunner.php
> Add ApplicationRunner class

- composer.json
- src/ApplicationRunner.php
- tests/functional/EventListenerConfigurationTest.php
| Fixed issues  | ❌
Won't work without yiisoft/yii-event#22 merged
> Add event listener checker

- config/packages/yiisoft/middleware-dispatcher/config/dist/web.php
- config/packages/yiisoft/middleware-dispatcher/config/web.php
- yii
- yii.bat
| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/112
> Move console entry point to the application

- public/index-test.php
| Fixed issues  | https://github.com/yiisoft/app-api/issues/50
> Fix #13: Use ApplicationRunner in index-test.php

- config/packages/yiisoft/view/params.php
- src/Formatter/ApiResponseFormatter.php
| Fixed issues  | https://github.com/yiisoft/view/issues/156
Waiting: https://github.com/yiisoft/view/pull/157
> Update view config params due to yiisoft/view changes

- src/Auth/AuthRequest.php
see https://github.com/yiisoft/validator/pull/134
> Adopt to new yiisoft/validator

- composer.json
- config/packages/yiisoft/yii-debug-api/params.php
- config/packages/yiisoft/yii-debug/params.php
> Add Debug Viewer

- composer.json
> Add serve command to composer scripts

- .editorconfig
- .github/workflows/build.yml
- .github/workflows/static.yml
- .scrutinizer.yml
- composer.json
- docker-compose.yml
> Raise minimum PHP requirements to ^8.0

- composer.json
- config/bootstrap.php
- config/packages/yiisoft/yii-debug/params.php
- config/providers.php
- src/ApplicationRunner.php
> New providers

- public/index-test.php
- public/index.php
- src/ApplicationRunner.php
- yii
| Fixed issues  | https://github.com/yiisoft/config/pull/73
> Adjust config

- composer.json
- config/common/logger.php
- config/packages/yiisoft/user/web.php
- config/packages/yiisoft/view/params.php
- config/web/application.php
> Adopt to `yiisoft/definitions`

- composer.json
- config/web/application.php
- public/index-test.php
- public/index.php
- src/Handler/NotFoundHandler.php
- src/Handler/ThrowableHandler.php
- src/Runner/BootstrapRunner.php
- src/Runner/ConsoleApplicationRunner.php
- src/Runner/WebApplicationRunner.php
- tests/_support/CliTester.php
- tests/cli.suite.yml
- tests/cli/ConsoleCest.php
- yii
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Runner class improvements.

- src/Runner/ConfigFactory.php
> Fix ConfigFactory

- config/web/application.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | https://github.com/yiisoft/middleware-dispatcher/issues/43
> Adopt middleware-dispatcher changes

- .scrutinizer.yml
- codeception.yml
- public/index.php
> Fix scrutinizer-ci.

- composer.json
- config/params.php
Waiting: https://github.com/yiisoft/yii-middleware/pull/1
> Replace usage of yiisoft/yii-web to yiisoft/yii-http

- tests/functional/EventListenerConfigurationTest.php
| Fixed issues  | https://github.com/yiisoft/di/pull/276
> Adopt to DI changes

- tests/functional/EventListenerConfigurationTest.php
| Fixed issues  |  -
Waiting:
https://github.com/yiisoft/yii-runner/pull/6
https://github.com/yiisoft/yii-runner-http/pull/13
https://github.com/yiisoft/yii-runner-console/pull/11
> Update EventListenerConfigurationTest due improve ConfigFactory::create()

- config/params.php
- config/routes.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | See https://github.com/yiisoft/yii-swagger/pull/48
> Adapt to yii-swagger changes

- config/web/middleware-dispatcher.php
- src/Auth/AuthRequest.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Re-define middleware factory

- .github/workflows/build.yml
- .github/workflows/static.yml
- composer.json
> Add PHP 8.1 support to GitHub workflow, update dev-dependencies

- composer.json
- config/web/middleware-dispatcher.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | https://github.com/yiisoft/middleware-dispatcher/pull/55
> Adapt to `yiisoft/middleware-dispatcher`

- .github/workflows/build.yml
- phpunit.xml.dist
> Fix autoload file path

- CHANGELOG.md
- phpunit.xml.dist
> Remove placeholders

- composer.json
- config/common/router.php
- config/common/translator.php
- config/params.php
- config/web/application.php
- resources/messages/en/app.php
- resources/messages/ru/app.php
- src/Handler/NotFoundHandler.php
- tests/Acceptance/SiteCest.php
> Add translator

- composer.json
> Fix tests run

- config/prod/params.php
- config/test/params.php
> Disable yii-debug on specific environments

- composer.json
> Use stable version of validator

- .styleci.yml
- config/web/di/application.php
- public/index.php
> Update StyleCI config

- composer.json
- config/web/di/application.php
- config/web/params.php
> :warning: Depends on https://github.com/yiisoft/yii-debug-api/pull/113.
> Sync with middleware

- composer.json
> Move yii-debug-api to require-dev

- config/common/routes.php
https://github.com/yiisoft/yii-swagger/pull/79
> Add cors for swagger

- config/common/routes.php
> Change swagger action class 

- .editorconfig
- Makefile
- config/common/di/router.php
- config/web/events.php
- configuration.php
> Add Makefile + Fix configuration

- autoload.php
- psalm.xml
- src/Http/ApiResponseDataFactory.php
- src/Installer.php
- tests/Unit/Http/ApiResponseDataFactoryTest.php
> Increase psalm level

- README.md
> Fix badge `README.md`.

- src/Controller/IndexController.php
- src/Http/ApiResponseData.php
| Is bugfix?    | ✔️?
| New feature?  | ✔️?
| Breaks BC?    | ❌?
| Fixed issues  |  Part of problem from [https://github.com/yiisoft/yii-swagger/issues/84](https://github.com/yiisoft/yii-swagger/issues/84)
> Update annotations for OpenAPI

- composer.json
- config/common/routes.php
- public/.htaccess
- Added .htaccess (ready for open "/docs")
- add yiisoft/cache-file (Throw exception)
- Fixed swagger namespaces and handler name (Just do not work on start)
> Some fixes to make the template start comfortable.

- .gitattributes
- .gitignore
> Add `export-ignore` section to `.gitattributes` + Remove `composer.lock` from `.gitignore`

- composer.json
> Update composer.json #205

- README.md
- config/common/di/cache.php
> Remove scrutinizer badge

- composer.json
- tests/Functional/InfoControllerTest.php
- tests/Support/FunctionalTester.php
> Replace "Yii Testing" to "Yii HTTP Runner" usage

- composer.json
- config/common/params.php
> Remove Yii Assets dependency

- src/Environment.php
Related to https://github.com/yiisoft/app/pull/399
> Improve message for missing or invalid APP_ENV

- composer.json
> Add "bump-after-update: true" + cleanup `composer.json`

- config/web/di/application.php
- src/Exception/ApplicationException.php
- src/Http/ExceptionMiddleware.php
> Use `UserException` instead of `ApplicationException`

- rector.php
> Update rector configuration
